---
- name: 'Ensure /data/apps exists'
  become: yes
  become_user: root
  file:
    path: '{{ item }}'
    state: directory
    mode: 0777
  with_items:
    - '/data'
    - '/data/apps'

- name: Download git repo.
  become: yes
  become_user: root
  #command: 'git -c http.sslVerify=false clone -b {{ branch }} --single-branch https://{{ user }}:{{ pass }}@{{ git_link }}'
  shell: 'git clone https://github.com/rea-cruitment/simple-sinatra-app.git'
  args:
    chdir: '/data/apps'

- name: 'Give permission to git directories'
  become: yes
  become_user: root
  file:
    path: '/data/apps'
    state: directory
    mode: 0777
    recurse: yes

- name: Install the app.
  become: yes
  become_user: root
  ignore_errors: yes
  shell: 'bundle install'
  environment:
    PATH: /usr/local/bin/bundle:{{ ansible_env.PATH }}
  args:
    chdir: '/data/apps/simple-sinatra-app'


- name: Run the app.
  become: yes
  become_user: root
  shell: 'nohup bundle exec rackup -p 80 --host {{ ipaddress }} </dev/null >/dev/null 2>&1 &'
  args:
    chdir: '/data/apps/simple-sinatra-app'
    executable: /bin/bash
  environment:
    PATH: /usr/local/bin/bundle:{{ ansible_env.PATH }} 